get:
  tags:
    - Products
  summary: List product categories
  operationId: listProductCategories
  responses:
    "200":
      description: Product categories returned successfully.
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../components/schemas/index.yaml#/ProductCategory
