DROP TRIGGER IF EXISTS trg_payment_updated_at ON payment;
DROP TRIGGER IF EXISTS trg_invoice_updated_at ON invoice;
DROP TRIGGER IF EXISTS trg_delivery_updated_at ON delivery;
DROP TRIGGER IF EXISTS trg_warehouse_updated_at ON warehouse;
DROP TRIGGER IF EXISTS trg_sales_order_updated_at ON sales_order;
DROP TRIGGER IF EXISTS trg_quote_updated_at ON quote;
DROP TRIGGER IF EXISTS trg_product_updated_at ON product;
DROP TRIGGER IF EXISTS trg_product_category_updated_at ON product_category;
DROP TRIGGER IF EXISTS trg_opportunity_updated_at ON opportunity;
DROP TRIGGER IF EXISTS trg_customer_address_updated_at ON customer_address;
DROP TRIGGER IF EXISTS trg_customer_contact_updated_at ON customer_contact;
DROP TRIGGER IF EXISTS trg_customer_updated_at ON customer;
DROP TRIGGER IF EXISTS trg_pipeline_stage_updated_at ON pipeline_stage;
DROP TRIGGER IF EXISTS trg_sales_pipeline_updated_at ON sales_pipeline;
DROP TRIGGER IF EXISTS trg_app_user_updated_at ON app_user;

DROP TABLE IF EXISTS activity_log;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS invoice;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS inventory_movement;
DROP TABLE IF EXISTS inventory_balance;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS sales_order_item;
DROP TABLE IF EXISTS sales_order;
DROP TABLE IF EXISTS quote_item;
DROP TABLE IF EXISTS quote;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS opportunity;
DROP TABLE IF EXISTS customer_address;
DROP TABLE IF EXISTS customer_contact;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS pipeline_stage;
DROP TABLE IF EXISTS sales_pipeline;
DROP TABLE IF EXISTS app_user;

DROP FUNCTION IF EXISTS set_updated_at();

DROP TYPE IF EXISTS payment_status;
DROP TYPE IF EXISTS payment_method;
DROP TYPE IF EXISTS invoice_status;
DROP TYPE IF EXISTS delivery_status;
DROP TYPE IF EXISTS inventory_movement_type;
DROP TYPE IF EXISTS sales_order_status;
DROP TYPE IF EXISTS quote_status;
DROP TYPE IF EXISTS opportunity_status;
DROP TYPE IF EXISTS address_type;
DROP TYPE IF EXISTS customer_status;
DROP TYPE IF EXISTS customer_type;
DROP TYPE IF EXISTS user_role;
